name: "Sync"
on:
  workflow_dispatch:
  schedule:
    # 每天8,12,16,20点检测一次
    - cron: '0 0,4,8,12 * * *'
permissions: {}
jobs:
  sync:
    runs-on: ubuntu-24.04
    name: sync
    steps:
      - uses: actions/checkout@v4
      - name: install skopeo
        run: |
          sudo curl -sSL https://github.com/lework/skopeo-binary/releases/latest/download/skopeo-linux-amd64 -o /usr/bin/skopeo && sudo chmod +x /usr/bin/skopeo
          skopeo --version
      - uses: actions/setup-node@v3
        with:
          node-version: lts/Hydrogen
      - name: install dependencies
        run: npm install semver cheerio js-yaml
      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const yaml = require('js-yaml');
            let images = yaml.load(fs.readFileSync('images.yml', 'utf8'));
            for (let registry of Object.keys(images)) {
              let distNamespace = `registry.cn-beijing.aliyuncs.com/bjzyhk_${registry.replace('.', '_')}`;
              for (let image of images[registry]) {
                let sourceImage = `${registry}/${image}`;
                let distImage = `${distNamespace}/${image.replace('/', '_s_')}`;
                console.log(`${sourceImage} => ${distImage}`);
                await exec.exec('/usr/bin/skopeo', ['copy', '--src-tls-verify=false', '--dest-tls-verify=false', '--multi-arch=all', `docker://${sourceImage}`, `docker://${distImage}`])
              }
            }
